import React, { useState } from 'react';
import * as FaIcons from 'react-icons/fa';
import SafeIcon from '../common/SafeIcon';

const { FaChevronDown, FaChevronUp } = FaIcons;

function FAQs() {
  const [openItems, setOpenItems] = useState({});

  const faqItems = [
    {
      question: 'How secure are the passwords generated by this tool?',
      answer: 'Our password generator creates truly random passwords using cryptographically secure methods. All generation happens locally in your browser, ensuring your passwords are never transmitted or stored on our servers.'
    },
    {
      question: 'Is it safe to check my password against the breach database?',
      answer: 'Yes, it\'s completely safe. We use the k-anonymity method from Have I Been Pwned. Only the first 5 characters of your password\'s SHA-1 hash are sent to the API, and the actual password never leaves your browser.'
    },
    {
      question: 'What makes a password strong?',
      answer: 'A strong password is typically at least 12 characters long and includes a mix of uppercase letters, lowercase letters, numbers, and symbols. Avoid common words, personal information, and predictable patterns.'
    },
    {
      question: 'Do you store my passwords or personal information?',
      answer: 'No, we do not store any passwords or personal information. All password generation happens locally in your browser. We only use local storage to save your password format preferences on your device.'
    },
    {
      question: 'How often should I change my passwords?',
      answer: 'For important accounts, it\'s recommended to change passwords every 3-6 months. However, if you suspect any account has been compromised, change that password immediately.'
    }
  ];

  const toggleItem = (index) => {
    setOpenItems(prev => ({
      ...prev,
      [index]: !prev[index]
    }));
  };

  return (
    <section id="faqs" className="bg-white rounded-lg shadow-md p-6 mb-6">
      <h2 className="text-2xl font-bold text-gray-800 mb-4">Frequently Asked Questions</h2>
      <div className="space-y-4">
        {faqItems.map((item, index) => (
          <div key={index} className="border-b border-gray-200 pb-4">
            <div
              className="flex justify-between items-center cursor-pointer font-semibold"
              onClick={() => toggleItem(index)}
            >
              <span>{item.question}</span>
              <SafeIcon icon={openItems[index] ? FaChevronUp : FaChevronDown} />
            </div>
            {openItems[index] && (
              <div className="mt-2 text-gray-600">
                <p>{item.answer}</p>
              </div>
            )}
          </div>
        ))}
      </div>
    </section>
  );
}

export default FAQs;